services:
  - type: web
    name: site-name-here
    runtime: static
    buildCommand: bundle install && npm ci && bundle exec jekyll build
    staticPublishPath: _site
    pullRequestPreviewsEnabled: true
